# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Exclude list
exclude: [
  'node_modules',
  'bower_components',
  'css',
  '_scss',
  'package.json',
  'bower.json',
  'Gruntfile.js',
  'README.md'
]

# Don't erase CSS when re-building
keep_files: ['_site/css']
